20170603 make models
breynolds-dev/dnd5e-api-python pull request #1
Opened 2017-06-03 17:17 UTC by firedrow

I believe the models are setup properly, according to the ruby schema and how I viewed your languages/race association table.

2017-06-04 20:32 UTC, breynolds-dev requested changes

2017-06-04 20:32 UTC, breynolds-dev commented on dnd5eApi/models/abilities.py
> +from dnd5eApi.models.racial_languages import class_primary_ability
this is using `dnd5eApi.models.racial_languages` should this be `dnd5eApi.models.class_primary_ability`?

2017-06-04 20:32 UTC, breynolds-dev commented on dnd5eApi/models/class_names.py
> +from dnd5eApi.models.racial_languages import class_primary_ability
this is the same as above, should this be using `dnd5eApi.models.class_primary_ability`

2017-06-04 20:32 UTC, breynolds-dev commented on dnd5eApi/models/class_primary_ability.py
> +    db.Column('className_id', db.Integer, db.ForeignKey('className.id')),
I know we've kind of mixed styles here but should this be `class_name` instead of `className`?

2017-06-04 20:32 UTC, breynolds-dev commented on dnd5eApi/models/class_saving_throws.py
> +    db.Column('className_id', db.Integer, db.ForeignKey('className.id')),
same as above, `className` vs `class_name`

2017-06-04 20:32 UTC, breynolds-dev commented on dnd5eApi/models/feats.py
> +  #races = db.relationship( 'Race', secondary = racial_languages, backref = db.backref( 'language', lazy = 'dynamic' ) )
Were we missing the table here to build this relationship?

Or is this relationship just here as a placeholder

2017-06-04 21:06 UTC, firedrow commented on dnd5eApi/models/abilities.py
> +from dnd5eApi.models.racial_languages import class_primary_ability
This is correct, overlooked.

2017-06-04 21:06 UTC, firedrow commented on dnd5eApi/models/class_names.py
> +from dnd5eApi.models.racial_languages import class_primary_ability
This is correct, overlooked.

2017-06-04 21:07 UTC, firedrow commented on dnd5eApi/models/class_primary_ability.py
> +    db.Column('className_id', db.Integer, db.ForeignKey('className.id')),
If that's how we'd prefer it, yes.

2017-06-04 21:07 UTC, firedrow commented on dnd5eApi/models/class_saving_throws.py
> +    db.Column('className_id', db.Integer, db.ForeignKey('className.id')),
If that's how we'd prefer it, yes.

2017-06-04 21:12 UTC, firedrow commented on dnd5eApi/models/feats.py
> +  #races = db.relationship( 'Race', secondary = racial_languages, backref = db.backref( 'language', lazy = 'dynamic' ) )
It is a placeholder for now.  I didn't see a reference for this in your ruby code, so I figured you had not developed the linker table yet.

2017-06-06 01:42 UTC, breynolds-dev approved these changes

2017-06-06 01:43 UTC, merged